default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: utf8
  reconnect: true

development:
  <<: *default
  database: db_nsoj_dev

test:
  <<: *default
  database: db_nsoj_test

production:
  <<: *default
  host: ec2-54-227-246-11.compute-1.amazonaws.com
  database: d163u7pb7arsqd
  username: nqsvujnychavbw
  password: 'x76n8S-JpU4TKA3YC8X2tLclYE'
  port: 5432