development: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: utf8
  reconnect: true
  reaping_frequency: 10
  database: db_nsoj_dev

test:
  <<: *default
  database: db_nsoj_test

production:
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
  url:  <%= ENV.fetch("DATABASE_URL", "") %>